CREATE DATABASE IF NOT EXISTS `ruin` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE USER 'ruin'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'ruin';
GRANT USAGE ON *.* TO 'ruin'@'localhost';
ALTER USER 'ruin'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, LOCK TABLES ON `ruin`.* TO 'ruin'@'localhost';
ALTER USER 'ruin'@'localhost' ;
